server:
  port: 8081
spring:
  application:
    name: serie-service
  zipkin:
    baseUrl: http://localhost:9411/
  mongodb:
    embedded:
      version: 3.6.0
  data:
    mongodb:
      database: test
      port: 27017

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
